### ISSUE TITLE
Update README with details

### ISSUE THREAD

**Issue by elenagan** [UBC-MDS/BrokkR#4]
- [x] a summary paragraph that describes the project at a high level

- [x] a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)

- [x] a paragraph describing where your packages fit into the R ecosystem (are there any other R packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).

**Comment by mikeguron** [comment]
Updated README file with all the sections as outlined above
